### PR TITLE
Feature/number guessing game

### LINKED ISSUE #3: Guess the Number (C++)
A number guessing game written in C++. Try to guess the randomly generated number.

### PR DESCRIPTION
**Pull request by manaswini-ks**
fixes #3 
I have added the code for a basic Number guessing game in C++ with clear docoumentation containing example gameplay as well.
Please do check it out and merge it to the repo under the hacktoberfest label

### CODE REVIEW

**Comment by ayush-raj13** [comment]
guess-number.cpp is empty

**Comment by manaswini-ks** [comment]
oh okay, i'll check that once
thank you

**Comment by manaswini-ks** [comment]
I think this should work

**Comment by manaswini-ks** [comment]
could you please add the hacktoberfest label for the same?

**Pull request merged**
