### PR TITLE
Added Rock Paper Scissors game

### PR DESCRIPTION
**Pull request by Anuj-Gill**
I've made an exciting Rock, Paper, Scissors game using HTML, CSS & JS. You can play it manually or let it play itself. Keeps track of your scores until you decide to start over. 
You can check it out [here](https://anuj-gill.github.io/Rock_Paper_Scissors/).

### CODE REVIEW

**Comment by ayush-raj13** [comment]
Nice project!

**Comment by Anuj-Gill** [comment]
Hi @ayush-raj13,

I noticed that my pull request (#49) which added the "Rock Paper Scissors game" was recently reverted. I'm curious to understand the reason behind the revert so that I can improve my contributions in the future. Could you please provide some context or feedback on why the changes were reverted?

**Comment by ayush-raj13** [comment]
The directory was empty. You can create another PR with the files.

**Comment by Anuj-Gill** [comment]
Ok, it seems there was a mistake from my side while uploading the files. Will add the files again. Thankyou for clarifying it. Also, I have made a calculator using JS and local storage, can I create a pull request for that too?? Because there is already a Calculator project in Js folder.

**Comment by ayush-raj13** [comment]
Yes, you can add your Calculator app. Just keep your folder name slightly different

**Pull request merged**
