### PR TITLE
Feature/new mini project

### PR DESCRIPTION
**Pull request by Rahban1**
I have a made a simple timer in **C++**. It is a simple C++ project for beginners.

### CODE REVIEW

**Comment by ayush-raj13** [comment]
Create a separate folder inside C++ directory

**Comment by ayush-raj13** [comment]
Create a folder named Timer inside C++. Put your files inside Timer folder

**Comment by ayush-raj13** [comment]
LGTM 👍

**Comment by Rahban1** [comment]
sir, you were quite helpful, thank you 
would love to connect 
linkedin: https://www.linkedin.com/in/rahban-ghani-b455261a8/

**Comment by ayush-raj13** [comment]
Funny thing, we are already connected on LinkedIn 😂

**Comment by Rahban1** [comment]
wow! I didn't even realize. small world :)

**Pull request merged**
