### PR TITLE
Temprature convertor

### LINKED ISSUE #43: Temperature-Convertor
I can contribute a mini project of Temperature convertor app.

### PR DESCRIPTION
**Pull request by shrutiiigupta**
Added temprature convertor app
closes #43

### CODE REVIEW

**Comment by ayush-raj13** [comment]
Temperature_Convertor directory is empty

**Comment by shrutiiigupta** [comment]
Sorry, I added them now

**Review by geekyharsh05 — APPROVED** [review]

**Review by geekyharsh05 — COMMENTED** [review]
## Improvements to Temperature Conversion Code

**Description:**
This issue aims to enhance the existing temperature conversion JavaScript code by implementing improvements related to input validation, rounding, constant use for conversion factors, and better error handling.

**Proposed Changes:**

1. **Input Validation:** Currently, the code does not handle invalid input. We should implement input validation to ensure that the user provides valid numeric input. This will prevent unexpected behavior or errors when non-numeric characters are entered.

2. **Rounding:** Temperature values should be rounded to two decimal places to improve accuracy and user-friendliness. We can achieve this by using the `toFixed()` method.

3. **Constants for Conversion Factors:** The code currently hardcodes conversion factors (e.g., 1.8 and 273.15). To enhance readability and maintainability, these factors should be defined as named constants.

4. **Error Handling:** While not explicitly implemented in the code, we need to establish a foundation for handling invalid input gracefully, such as displaying an error message to the user.

5. **Event Listeners:** Event listeners should be added to each input field (`celsiusInput`, `fahrenheitInput`, `kelvinInput`) to trigger the `calculate` function when the user enters or changes values. This ensures that the conversion is updated in real-time as the user interacts with the input fields.

6. **Improved Variable Names:** Variable names like `celsiusInput`, `fahrenheitInput`, and `kelvinInput` should be used for improved code readability, making it clear which elements they reference.

**Additional Notes:**

This code enhancement will not only make the code more robust and user-friendly but also set a foundation for future improvements and error handling. It is essential for maintaining code quality and ensuring a smooth user experience.

**Comment by ayush-raj13** [comment]
Great work, thank you for providing the description. Keep contributing 🙂

**Pull request merged**
